/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as TrainerIntegrationsRouteImport } from './routes/trainer.integrations'
import { Route as TrainerEventTypesRouteImport } from './routes/trainer.event-types'
import { Route as TrainerCalendarRouteImport } from './routes/trainer.calendar'
import { Route as TrainerAvailabilityRouteImport } from './routes/trainer.availability'
import { Route as ClientStoreRouteImport } from './routes/client.store'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientBookRouteImport } from './routes/client.book'
import { Route as TrainerClientsIndexRouteImport } from './routes/trainer.clients.index'
import { Route as TrainerClientsIdRouteImport } from './routes/trainer.clients.$id'
import { Route as ClientBookingsBookingIdRouteImport } from './routes/client.bookings.$bookingId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const TrainerIntegrationsRoute = TrainerIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerEventTypesRoute = TrainerEventTypesRouteImport.update({
  id: '/event-types',
  path: '/event-types',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerCalendarRoute = TrainerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAvailabilityRoute = TrainerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientStoreRoute = ClientStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookRoute = ClientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClientRoute,
} as any)
const TrainerClientsIndexRoute = TrainerClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerClientsIdRoute = TrainerClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientBookingsBookingIdRoute = ClientBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => ClientRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/client/book': typeof ClientBookRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/store': typeof ClientStoreRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/event-types': typeof TrainerEventTypesRoute
  '/trainer/integrations': typeof TrainerIntegrationsRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/client/bookings/$bookingId': typeof ClientBookingsBookingIdRoute
  '/trainer/clients/$id': typeof TrainerClientsIdRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client/book': typeof ClientBookRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/store': typeof ClientStoreRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/event-types': typeof TrainerEventTypesRoute
  '/trainer/integrations': typeof TrainerIntegrationsRoute
  '/client': typeof ClientIndexRoute
  '/trainer': typeof TrainerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/client/bookings/$bookingId': typeof ClientBookingsBookingIdRoute
  '/trainer/clients/$id': typeof TrainerClientsIdRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/client/book': typeof ClientBookRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/store': typeof ClientStoreRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/calendar': typeof TrainerCalendarRoute
  '/trainer/event-types': typeof TrainerEventTypesRoute
  '/trainer/integrations': typeof TrainerIntegrationsRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/client/bookings/$bookingId': typeof ClientBookingsBookingIdRoute
  '/trainer/clients/$id': typeof TrainerClientsIdRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/forgot-password'
    | '/reset-password'
    | '/trainer'
    | '/client/book'
    | '/client/settings'
    | '/client/store'
    | '/trainer/availability'
    | '/trainer/calendar'
    | '/trainer/event-types'
    | '/trainer/integrations'
    | '/client/'
    | '/trainer/'
    | '/api/public/stripe-webhook'
    | '/client/bookings/$bookingId'
    | '/trainer/clients/$id'
    | '/trainer/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/client/book'
    | '/client/settings'
    | '/client/store'
    | '/trainer/availability'
    | '/trainer/calendar'
    | '/trainer/event-types'
    | '/trainer/integrations'
    | '/client'
    | '/trainer'
    | '/api/public/stripe-webhook'
    | '/client/bookings/$bookingId'
    | '/trainer/clients/$id'
    | '/trainer/clients'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/client'
    | '/forgot-password'
    | '/reset-password'
    | '/trainer'
    | '/client/book'
    | '/client/settings'
    | '/client/store'
    | '/trainer/availability'
    | '/trainer/calendar'
    | '/trainer/event-types'
    | '/trainer/integrations'
    | '/client/'
    | '/trainer/'
    | '/api/public/stripe-webhook'
    | '/client/bookings/$bookingId'
    | '/trainer/clients/$id'
    | '/trainer/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrainerRoute: typeof TrainerRouteWithChildren
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/trainer/integrations': {
      id: '/trainer/integrations'
      path: '/integrations'
      fullPath: '/trainer/integrations'
      preLoaderRoute: typeof TrainerIntegrationsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/event-types': {
      id: '/trainer/event-types'
      path: '/event-types'
      fullPath: '/trainer/event-types'
      preLoaderRoute: typeof TrainerEventTypesRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/calendar': {
      id: '/trainer/calendar'
      path: '/calendar'
      fullPath: '/trainer/calendar'
      preLoaderRoute: typeof TrainerCalendarRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/availability': {
      id: '/trainer/availability'
      path: '/availability'
      fullPath: '/trainer/availability'
      preLoaderRoute: typeof TrainerAvailabilityRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/store': {
      id: '/client/store'
      path: '/store'
      fullPath: '/client/store'
      preLoaderRoute: typeof ClientStoreRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/book': {
      id: '/client/book'
      path: '/book'
      fullPath: '/client/book'
      preLoaderRoute: typeof ClientBookRouteImport
      parentRoute: typeof ClientRoute
    }
    '/trainer/clients/': {
      id: '/trainer/clients/'
      path: '/clients'
      fullPath: '/trainer/clients/'
      preLoaderRoute: typeof TrainerClientsIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/clients/$id': {
      id: '/trainer/clients/$id'
      path: '/clients/$id'
      fullPath: '/trainer/clients/$id'
      preLoaderRoute: typeof TrainerClientsIdRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/bookings/$bookingId': {
      id: '/client/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/client/bookings/$bookingId'
      preLoaderRoute: typeof ClientBookingsBookingIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientRouteChildren {
  ClientBookRoute: typeof ClientBookRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientStoreRoute: typeof ClientStoreRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientBookingsBookingIdRoute: typeof ClientBookingsBookingIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookRoute: ClientBookRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientStoreRoute: ClientStoreRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientBookingsBookingIdRoute: ClientBookingsBookingIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface TrainerRouteChildren {
  TrainerAvailabilityRoute: typeof TrainerAvailabilityRoute
  TrainerCalendarRoute: typeof TrainerCalendarRoute
  TrainerEventTypesRoute: typeof TrainerEventTypesRoute
  TrainerIntegrationsRoute: typeof TrainerIntegrationsRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  TrainerClientsIdRoute: typeof TrainerClientsIdRoute
  TrainerClientsIndexRoute: typeof TrainerClientsIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAvailabilityRoute: TrainerAvailabilityRoute,
  TrainerCalendarRoute: TrainerCalendarRoute,
  TrainerEventTypesRoute: TrainerEventTypesRoute,
  TrainerIntegrationsRoute: TrainerIntegrationsRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  TrainerClientsIdRoute: TrainerClientsIdRoute,
  TrainerClientsIndexRoute: TrainerClientsIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrainerRoute: TrainerRouteWithChildren,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
